### ISSUE TITLE
[FEATURE] Alternative Publishing Fonts & Font Advice

### ISSUE THREAD

**Issue by msprijatelj** [Tetragramm/lancer-field-guide-template#2]
While the CompCon font is free to use, [Arial](https://www.fonts.com/font/monotype/arial/licenses) and [Consolas](https://www.fonts.com/font/microsoft-corporation/consolas/licenses) used in the [FieldGuide.sty](https://github.com/Tetragramm/lancer-field-guide-template/blob/master/FieldGuide.sty#L44-L56) usually require a license to be purchased when used in a electronic publication. To help potential publishers avoid pitfalls regarding font licensing, it may be helpful to mention the need for such licenses in order to create an electronic publication. Along with this advice, it may be helpful to provide some substitute fonts with open licenses for stress-free publishing. Some recommendations are provided below:

### Arial replacements
- [Arimo](https://fonts.google.com/specimen/Arimo/about?query=arimo), available under [Apache License, version 2.0](https://www.apache.org/licenses/LICENSE-2.0)
- [Liberation Sans](https://www.fontsquirrel.com/fonts/liberation-sans), available under the [Open Font License](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)

### Consolas replacements
- [Inconsolata](https://fonts.google.com/specimen/Inconsolata/about?query=inconsolata), available under the [Open Font License](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [Ubuntu Mono](https://fonts.google.com/specimen/Ubuntu+Mono/about?query=ubuntu), available under the [Ubuntu Font License](https://ubuntu.com/legal/font-licence)

**Comment by Tetragramm** [comment]
An excellent suggestion.  The fonts you found are much closer matches than my previous finds.  Close enough that I've just set Arimo and Inconsolata as default.

**Comment by msprijatelj** [comment]
I know that the official Massif Press publications use Helvetica and Consolas, so you were pretty much on the nose with your initial picks! It's just inconvenient that they're not open fonts. Glad this issue could help!
